# Generated by Django 5.2.8 on 2025-11-13 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('TAMBAK', 'Tambak'), ('PENGUMPUL', 'Pengumpul'), ('PABRIK', 'Pabrik Pengolahan'), ('EKSPORTIR', 'Eksportir')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(help_text='ID Unik Lot, misal: A-001', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('HOLD', 'Ditahan'), ('INVESTIGATE', 'Investigasi')], default='OK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tracker.lot')),
                ('node_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='tracker.node')),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='tracker.node')),
            ],
        ),
        migrations.CreateModel(
            name='QCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='Contoh: Cesium', max_length=100)),
                ('metric_value', models.FloatField()),
                ('unit', models.CharField(default='mg/kg', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_results', to='tracker.lot')),
                ('node_at', models.ForeignKey(help_text='Diuji di node mana', on_delete=django.db.models.deletion.PROTECT, to='tracker.node')),
            ],
        ),
    ]
