# Generated by Django 5.2.8 on 2025-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcresult',
            name='is_contaminated',
            field=models.BooleanField(default=False, help_text='True jika nilai melewati batas'),
        ),
        migrations.AddField(
            model_name='qcresult',
            name='limit_value',
            field=models.FloatField(blank=True, help_text='Batas maksimum yang diizinkan (opsional)', null=True),
        ),
    ]
