# Generated by Django 5.2.8 on 2025-11-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='public_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='lot',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='volume_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotmovement',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lotmovement',
            name='quantity_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('OK', 'Aman'), ('HOLD', 'Ditahan'), ('INVESTIGATE', 'Investigasi')], default='OK', max_length=20),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('FARM', 'Tambak / Farm'), ('COLLECTOR', 'Pengumpul'), ('PROCESSOR', 'Pabrik / Processor'), ('EXPORTER', 'Eksportir')], max_length=20),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_profile', to='tracker.node')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LAB_CERT', 'Sertifikat Lab'), ('FARM_CERT', 'Sertifikat Tambak'), ('EXPORT_DOC', 'Dokumen Ekspor'), ('OTHER', 'Lainnya')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.lot')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.farm')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='tracker.farm'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('EXPORT_REJECT', 'Penolakan Ekspor'), ('LAB_FAIL', 'Gagal Uji'), ('COMPLAINT', 'Keluhan Buyer')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='tracker.lot')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentRelatedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_lots', to='tracker.incident')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_incidents', to='tracker.lot')),
            ],
        ),
        migrations.CreateModel(
            name='PondLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('salinity_ppt', models.FloatField(blank=True, null=True)),
                ('feed_type', models.CharField(blank=True, max_length=100)),
                ('chemicals_used', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_logs', to='tracker.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('requested_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SAMPLED', 'Sampled'), ('SENT_TO_LAB', 'Sent to Lab')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplings', to='tracker.lot')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('limit_value', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='PASS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sampling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tracker.sampling')),
            ],
        ),
    ]
